// commented out so workbench can compile as this file is the first in the list to uglify "use strict";
/**
 * Created on 4/9/14.
 *
 * global constants and variable used by and shared between modules
 * should be first script file loaded or compiled as it defines
 * the MashableData object
 */

var MashableData = {
    globals: {
        version: '0.9',
        graphBluePrints: {}, //used to preload embedded graphs for high volume websites
        totalServerTime: 0,
        isEmbedded: (window.location.hostname.indexOf('www.mashabledata.com')===-1 || window.location.pathname.indexOf('workbench')===-1),
        isDev: (window.location.hostname.indexOf('www.mashabledata.com')!==-1 && window.location.pathname.indexOf('workbenchdev')!==-1),
        lang: {
            decimalPoint : '.',
            thousandsSep: ','
        },
        //ANNOTATOR
        BAND_TRANSPARENCY: 0.5,
        colorsPlotBands: ['aaaaaa', 'ffaaaa', 'aaffaa', 'aaaaff'],
        bubbleColor: 'pink',
        standardAnnotations: [],  //filled by API call on first use
        //WORKBENCH
        iconsHMTL: {
            mapset: '<span class="ui-icon ui-icon-mapset" title="series is part of a map set" alt="series is part of a map set"></span>',
            pointset: '<span class="ui-icon ui-icon-pointset" title="series is part of a set of markers (defined longitude and latitude)" alt="series is part of a set of markers (defined longitude and latitude)"></span>',
            hasCubeViz: '<span class="ui-icon ui-icon-cube" title="Themes may support supplemental visualizations" alt="Themes may support supplemental visualizations"></span>',
            hasHeatMap: '<span class="ui-icon ui-icon-mapset" title="contains a heat-map" alt="contains a heat-map"></span>',
            hasMarkerMap: '<span class="ui-icon ui-icon-pointset" title="contains sets of mapped markers (defined longitude and latitude)." alt="contains sets of mapped markers (defined longitude and latitude)."></span>',
            hasBubbleMap: '<span class="ui-icon ui-icon-bubble" title="bubble map of data aggregated into user-defined regions" alt="bubble map of data aggregated into user-defined regions"></span>'
        },
        themeCubes: {}, //stores {cubes: [{cubeid, name}...] under T+themeid key to eliminate repretative calls
        panelGraphs: {}, //oMyGraphs objects are copied and referenced by the tab's panelID (i.e. panelGraphs['graphTab1']).  Kept in sync by UI events.  Used by save/publish operations.
        //These 2 master objects contain representations of MySeries and MyGraphs.  They are filled by API calls and in turn are used populate the datatables
        MySets: {},  //referenced by 'S'+seriesid (i.e. oMySeries['S173937']). Filled from localstatoraged, API.getMySeries (header only; no data for speed), and when series is added from PublicSeries viewer.  Data fetched as needed.  Used to populate graph data (and vice-versa ) as possible.
        //var oPublicSeries = {}; //NOT USED. DataTables fetches directly from API.SearchSeries = endless scroll style fetch
        MyGraphs: {},  //complete fetch from API.GetMyGraphs.  Kept in sync with cloud by API.ManageMyGraphs and API.DeleteMyGraphs
        //var oPublicGraphs = {};  //NOT USED.  DataTables fetches directly from API.SearchGraphs = endless scroll style fetch TODO: show button not programmed

//GRAPH
        MAP_COLORS: {POS: '#0071A4', NEG: '#FF0000', MID: '#E5E5E5'},
        DEFAULT_RADIUS_SCALE: 30, //(px) used for both bubble maps and marker maps
        DEFAULT_RADIUS_FIXED: 10, //size of marker using full scaling and fixed radius
        hcColors: [
            '#2f7ed8',
            '#8bbc21',
            '#910000',
            '#1aadce',
            '#492970',
            '#f28f43',
            '#77a1e5',
            '#c42525',
            '#a6c96a',
            '#4572A7',
            '#AA4643',
            '#89A54E',
            '#80699B',
            '#3D96AE',
            '#DB843D',
            '#92A8CD',
            '#A47D7C',
            '#B5CA92',
            '#0d233a'  //very close to black
        ],
        primeColors: ['#008000', '#FF0000','#0000FF', '#FFFF00', '#FF9900', '#00FFFF', '#FF0000'],  //green, red, blue, yellow, orange, azure, lime green
        dashStyles: [
            'Solid',
            'Short Dash',
            'Short Dot',
            'Short Dash Dot',
            'Short Dash Dot Dot',
            'Dot',
            'Dash',
            'Long Dash',
            'Dash Dot',
            'Long Dash Dot',
            'Long Dash Dot Dot'
        ],
        period: {
            value:  { //used to determine rank and to set column widths
                N: 1000, //one second
                D: 24*3600*1000,
                W: 7*24*3600*1000,
                M: 30*24*3600*1000,
                Q: 365/4*24*3600*1000,
                SA: 365/2*24*3600*1000,
                A: 365*24*3600*1000
            },
            order: ['N','D','W','M','Q','SA','A'],
            name: {
                N: 'non period data',
                D: 'daily',
                W: 'weekly',
                M: 'monthly',
                Q: 'quarterly',
                SA: 'semiannual',
                A: 'annual'
            },
            units: {
                'N': "non-periodic data",
                'D': "day",
                'W': "week",
                'M': "month",
                'Q': "quarter",
                'SA': "half-year",
                'A': "year"
            }
        },
        op: {
            "value": {"+":1,"-":2,"*":3,"/":4},
            "cssClass": {"+":"op-addition","-":"op-subtraction","*":"op-multiply","/":"op-divide"}
        },
        mapBackground: '#AAAAAA',
        graphScriptFiles: ["/global/js/highcharts/js/modules/exporting.src.js","/global/js/colorpicker/jquery.colorPicker.min.js","/global/js/colour/Colour.js","/global/js/jvectormap/jquery-jvectormap-2.0.1.js"],
        rowPosition: {
            name: 0,
            units: 1,
            source: 2,
            notes: 3,
            region: 4,
            lat_lon: 5,
            date: 6,
            dataStart: 7
        },
        patVariable: /(\b[A-Z]{1,2}\b)/g,  //used to search and replace formula to use a passed in values object
        //SVGNS: "http://www.w3.org/2000/svg",
        isIE: /msie/i.test(navigator.userAgent) && !window.opera,
        mapModes: {
            "heat":  'colored heat map of values',
            "abs-change": 'colored heat map of changes',
            "percent-change": 'colored heat map of percent changes',
            "bubbles": 'overlay circles to show values',
            "change-bubbles": 'overlay circles to show changes',
            "correlation": 'correlation (requires two maps)',
            "treemap": 'abstract values to rectangles',
            "change-treemap": 'abstract change to rectangles',
            "min": 'color by date of minimum value',
            "max": 'color by date of maximum value'
        },
        translations: { //on graph load, a language is assigned to graph.literals from graph.mapConfig.lang (default is 'english')
            English: {
                vizMsg: 'click locations to compare',
                cubeMsg: 'click on map to view',
                in: ' in ',
                src: 'powered by MashableData',
                data: 'source data',
                cor: 'correlation coefficient ',
                rank: 'Rank',
                by: ' by ',
                "graph":"graph",
                "reset":"reset",
                "play":"play",
                "forward":"play",
                "backward":"backward",
                months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
                geonames: {
                    //for other languages, hash object of English country name keys (matching JVM names) with local country name values
                }
            },
            "French": {
                "vizMsg":"cliquez endroits pour comparer",
                "cubeMsg":"cliquez sur la carte pour voir",
                "in":"à",
                "src":"alimenté par MashableData",
                "data":"données source",
                "cor":"coefficient de corrélation",
                "rank":"Rang",
                "by":"par",
                "graph":"graphique",
                "reset":"remettre",
                "play":"jouer",
                "forward":"pas en avant",
                "backward":"pas en arrière",
                "months": ["janv.", "févr.", "mars", "avril", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
                geonames: {
                    "Belgium":"Belgique",
                    "Bulgaria":"Bulgarie",
                    "Bosnia and Herzegovina":"Bosnie Herzégovine",
                    "Bolivia":"Bolivie",
                    "Japan":"Japon",
                    "Benin":"Bénin",
                    "Bhutan":"Bhoutan",
                    "Jamaica":"Jamaïque",
                    "Brazil":"Brésil",
                    "The Bahamas":"Les Bahamas",
                    "Belarus":"Biélorussie",
                    "Russia":"Russie",
                    "Republic of Serbia":"République de Serbie",
                    "Lithuania":"Lituanie",
                    "Liberia":"Libéria",
                    "Romania":"Roumanie",
                    "Guinea Bissau":"Guinée-Bissau",
                    "Greece":"Grèce",
                    "Equatorial Guinea":"Guinée Equatoriale",
                    "Guyana":"Guyane",
                    "Georgia":"Géorgie",
                    "United Kingdom":"Royaume-Uni",
                    "Guinea":"Guinée",
                    "Gambia":"Gambie",
                    "Greenland":"Groenland",
                    "Kuwait":"Koweit",
                    "Western Sahara":"Sahara Occidental",
                    "Northern Cyprus":"Chypre-Nord",
                    "Jordan":"Jordanie",
                    "Croatia":"Croatie",
                    "Haiti":"Haïti",
                    "Hungary":"Hongrie",
                    "Puerto Rico":"Porto Rico",
                    "West Bank":"Cisjordanie",
                    "Papua New Guinea":"Papouasie Nouvelle Guinée",
                    "Peru":"Pérou",
                    "Poland":"Pologne",
                    "Zambia":"Zambie",
                    "Estonia":"Estonie",
                    "Egypt":"Egypte",
                    "South Africa":"Afrique Du Sud",
                    "Ecuador":"Equateur",
                    "Albania":"Albanie",
                    "Ethiopia":"Ethiopie",
                    "Spain":"Espagne",
                    "Eritrea":"Erythrée",
                    "Montenegro":"Monténégro",
                    "Morocco":"Maroc",
                    "Uzbekistan":"Ouzbékistan",
                    "Mongolia":"Mongolie",
                    "Macedonia":"Macédoine",
                    "Mauritania":"Mauritanie",
                    "Uganda":"Ouganda",
                    "Malaysia":"Malaisie",
                    "Mexico":"Mexique",
                    "Finland":"Finlande",
                    "Fiji":"Fidji",
                    "Falkland Islands":"Iles Malouines",
                    "Netherlands":"Pays-Bas",
                    "Norway":"Norvège",
                    "Namibia":"Namibie",
                    "New Caledonia":"Nouvelle-Calédonie",
                    "New Zealand":"Nouvelle Zélande",
                    "Nepal":"Népal",
                    "Ivory Coast":"Côte-d'Ivoire",
                    "Switzerland":"Suisse",
                    "Colombia":"Colombie",
                    "China":"Chine",
                    "Cameroon":"Cameroun",
                    "Chile":"Chili",
                    "Republic of the Congo":"République du Congo",
                    "Central African Republic":"République Centrafricaine",
                    "Democratic Republic of the Congo":"République démocratique du Congo",
                    "Czech Republic":"République Tchèque",
                    "Cyprus":"Chypre",
                    "Syria":"Syrie",
                    "Kyrgyzstan":"Kirghizstan",
                    "South Sudan":"Soudan du Sud",
                    "Cambodia":"Cambodge",
                    "El Salvador":"Le Salvador",
                    "Slovakia":"Slovaquie",
                    "South Korea":"Corée Du Sud",
                    "Slovenia":"Slovénie",
                    "North Korea":"Corée Du Nord",
                    "Somalia":"Somalie",
                    "Senegal":"Sénégal",
                    "Solomon Islands":"Iles Salomon",
                    "Saudi Arabia":"Arabie Saoudite",
                    "Sweden":"Suède",
                    "Sudan":"Soudan",
                    "Dominican Republic":"République Dominicaine",
                    "Denmark":"Danemark",
                    "Germany":"Allemagne",
                    "Yemen":"Yémen",
                    "Austria":"Autriche",
                    "Algeria":"Algérie",
                    "United States of America":"Etats-Unis d'Amerique",
                    "Latvia":"Lettonie",
                    "Lebanon":"Liban",
                    "Trinidad and Tobago":"Trinité-et-Tobago",
                    "Turkey":"Dinde",
                    "Tunisia":"Tunisie",
                    "East Timor":"Timor Oriental",
                    "Turkmenistan":"Turkménistan",
                    "Tajikistan":"Tadjikistan",
                    "Thailand":"Thaïlande",
                    "French Southern and Antarctic Lands":"Terres Australes et Antarctiques françaises",
                    "Chad":"Tchad",
                    "Libya":"Libye",
                    "United Arab Emirates":"Emirats Arabes Unis",
                    "Iraq":"Irak",
                    "Iceland":"Islande",
                    "Iran":"J'ai Couru",
                    "Armenia":"Arménie",
                    "Italy":"Italie",
                    "Vietnam":"Viêt-Nam",
                    "Argentina":"Argentine",
                    "Australia":"Australie",
                    "Israel":"Israël",
                    "India":"Inde",
                    "Tanzania":"Tanzanie",
                    "Azerbaijan":"Azerbaïdjan",
                    "Ireland":"Irlande",
                    "Indonesia":"Indonésie"
                }
            },
            "German": {
                "vizMsg":"Klicken Standorten zu vergleichen",
                "cubeMsg":"Klicken Sie auf der Karte zu sehen",
                "src":"angetrieben durch MashableData",
                "data":"Quelldaten",
                "cor":"Korrelationskoeffizient",
                "rank":"Rang",
                "by":"von",
                "graph":"graphen",
                "reset":"rücksetzen",
                "play":"spielen",
                "forward":"Schritt nach vorn",
                "backward":"Rückschritt",
                "months":["Jan.", "Feb.", "März", "Apr.", "Mai", "Juni", "Juli", "Aug.", "Sept.", "Okt.", "Nov.", "Dez."],
                geonames: {
                    "Bangladesh":"Bangladesch",
                    "Belgium":"Belgien",
                    "Bulgaria":"Bulgarien",
                    "Bosnia and Herzegovina":"Bosnien und Herzegowina",
                    "Bolivia":"Bolivien",
                    "Jamaica":"Jamaika",
                    "Brazil":"Brasilien",
                    "The Bahamas":"Die Bahamas",
                    "Belarus":"Weißrussland",
                    "Russia":"Russland",
                    "Rwanda":"Ruanda",
                    "Republic of Serbia":"Republik Serbien",
                    "Lithuania":"Litauen",
                    "Luxembourg":"Luxemburg",
                    "Romania":"Rumänien",
                    "Guinea Bissau":"Guinea-Bissau",
                    "Greece":"Griechenland",
                    "Equatorial Guinea":"Äquatorialguinea",
                    "United Kingdom":"Vereinigtes Königreich",
                    "Greenland":"Grönland",
                    "Western Sahara":"Westsahara",
                    "Northern Cyprus":"Nordzypern",
                    "Croatia":"Kroatien",
                    "Hungary":"Ungarn",
                    "West Bank":"Westjordanland",
                    "Papua New Guinea":"Papua-Neuguinea",
                    "Philippines":"Philippinen",
                    "Poland":"Polen",
                    "Zambia":"Sambia",
                    "Estonia":"Estland",
                    "Egypt":"Ägypten",
                    "South Africa":"Südafrika",
                    "Albania":"Albanien",
                    "Kazakhstan":"Kasachstan",
                    "Ethiopia":"Äthiopien",
                    "Spain":"Spanien",
                    "Moldova":"Moldawien",
                    "Madagascar":"Madagaskar",
                    "Morocco":"Marokko",
                    "Uzbekistan":"Usbekistan",
                    "Mongolia":"Mongolei",
                    "Macedonia":"Mazedonien",
                    "Mauritania":"Mauretanien",
                    "Mexico":"Mexiko",
                    "France":"Frankreich",
                    "Finland":"Finnland",
                    "Falkland Islands":"Falkland-Inseln",
                    "Netherlands":"Niederlande",
                    "Norway":"Norwegen",
                    "New Caledonia":"Neu-Kaledonien",
                    "New Zealand":"Neuseeland",
                    "Ivory Coast":"Elfenbeinküste",
                    "Switzerland":"Schweiz",
                    "Colombia":"Kolumbien",
                    "Cameroon":"Kamerun",
                    "Canada":"Kanada",
                    "Republic of the Congo":"Republik Kongo",
                    "Central African Republic":"Zentralafrikanische Republik",
                    "Democratic Republic of the Congo":"Demokratische Republik Kongo",
                    "Czech Republic":"Tschechische Republik",
                    "Cyprus":"Zypern",
                    "Cuba":"Kuba",
                    "Syria":"Syrien",
                    "Kyrgyzstan":"Kirgisistan",
                    "Kenya":"Kenia",
                    "South Sudan":"Süd-Sudan",
                    "Cambodia":"Kambodscha",
                    "Slovakia":"Slowakei",
                    "South Korea":"Südkorea",
                    "Slovenia":"Slowenien",
                    "North Korea":"Nordkorea",
                    "Solomon Islands":"Salomon-Inseln",
                    "Saudi Arabia":"Saudi-Arabien",
                    "Sweden":"Schweden",
                    "Dominican Republic":"Dominikanische Republik",
                    "Denmark":"Dänemark",
                    "Germany":"Deutschland",
                    "Yemen":"Jemen",
                    "Austria":"Österreich",
                    "Algeria":"Algerien",
                    "United States of America":"Vereinigte Staaten von Amerika",
                    "Latvia":"Lettland",
                    "Lebanon":"Libanon",
                    "Trinidad and Tobago":"Trinidad und Tobago",
                    "Turkey":"Truthahn",
                    "Tunisia":"Tunesien",
                    "East Timor":"Ost-Timor",
                    "Tajikistan":"Tadschikistan",
                    "French Southern and Antarctic Lands":"Französisch Süd- und Antarktisgebiete",
                    "Togo":"Gehen",
                    "Chad":"Tschad",
                    "Libya":"Libyen",
                    "United Arab Emirates":"Vereinigte Arabische Emirate",
                    "Iraq":"Irak",
                    "Iceland":"Island",
                    "Armenia":"Armenien",
                    "Italy":"Italien",
                    "Argentina":"Argentinien",
                    "Australia":"Australien",
                    "India":"Indien",
                    "Tanzania":"Tansania",
                    "Azerbaijan":"Aserbaidschan",
                    "Ireland":"Irland",
                    "Indonesia":"Indonesien",
                    "Qatar":"Katar",
                    "Mozambique":"Mosambik"
                }
            },
            "Spanish": {
                "vizMsg":"haga clic en Ubicaciones para comparar",
                "cubeMsg":"haga clic en el mapa para ver",
                "in":"en",
                "src":"impulsado por MashableData",
                "data":"datos de origen",
                "cor":"coeficiente de correlación",
                "rank":"Rango",
                "by":"por",
                "graph":"gráfico",
                "reset":"reajustar",
                "play":"jugar",
                "forward":"paso adelante",
                "backward":"paso atrás",
                "months": ["enero", "feb.", "marzo", "abr.", "mayo", "jun.", "jul.", "agosto", "set.", "oct.", "nov.", "dic."],
                geonames: {
                    "Belgium":"Bélgica",
                    "Bosnia and Herzegovina":"Bosnia y Herzegovina",
                    "Japan":"Japón",
                    "Bhutan":"Bhután",
                    "Brazil":"Brasil",
                    "The Bahamas":"Las Bahamas",
                    "Belarus":"Bielorrusia",
                    "Belize":"Belice",
                    "Russia":"Rusia",
                    "Rwanda":"Ruanda",
                    "Republic of Serbia":"República de Serbia",
                    "Lithuania":"Lituania",
                    "Luxembourg":"Luxemburgo",
                    "Romania":"Rumania",
                    "Greece":"Grecia",
                    "Equatorial Guinea":"Guinea Ecuatorial",
                    "Guyana":"Guayana",
                    "United Kingdom":"Reino Unido",
                    "Gabon":"Gabón",
                    "Greenland":"Groenlandia",
                    "Oman":"Omán",
                    "Somaliland":"Somalilandia",
                    "Western Sahara":"Sahara Occidental",
                    "Northern Cyprus":"Norte de Chipre",
                    "Jordan":"Jordania",
                    "Croatia":"Croacia",
                    "Haiti":"Haití",
                    "Hungary":"Hungría",
                    "West Bank":"Banco Oeste",
                    "Panama":"Panamá",
                    "Papua New Guinea":"Papúa Nueva Guinea",
                    "Peru":"Perú",
                    "Pakistan":"Pakistán",
                    "Philippines":"Filipinas",
                    "Poland":"Polonia",
                    "Egypt":"Egipto",
                    "South Africa":"Sudáfrica",
                    "Kazakhstan":"Kazajstán",
                    "Ethiopia":"Etiopía",
                    "Zimbabwe":"Zimbabue",
                    "Spain":"España",
                    "Moldova":"Moldavia",
                    "Morocco":"Marruecos",
                    "Uzbekistan":"Uzbekistán",
                    "Mali":"Malí",
                    "Malaysia":"Malasia",
                    "Mexico":"México",
                    "France":"Francia",
                    "Finland":"Finlandia",
                    "Falkland Islands":"Islas Malvinas",
                    "Netherlands":"Países Bajos",
                    "Norway":"Noruega",
                    "New Caledonia":"Nueva Caledonia",
                    "Niger":"Níger",
                    "New Zealand":"Nueva Zelanda",
                    "Ivory Coast":"Costa De Marfil",
                    "Switzerland":"Suiza",
                    "Cameroon":"Camerún",
                    "Canada":"Canadá",
                    "Republic of the Congo":"República del Congo",
                    "Central African Republic":"República Centroafricana",
                    "Democratic Republic of the Congo":"República Democrática del Congo",
                    "Czech Republic":"República Checa",
                    "Cyprus":"Chipre",
                    "Swaziland":"Swazilandia",
                    "Syria":"Siria",
                    "Kyrgyzstan":"Kirguistán",
                    "Kenya":"Kenia",
                    "South Sudan":"Sudán Del Sur",
                    "Cambodia":"Camboya",
                    "Slovakia":"Eslovaquia",
                    "South Korea":"Corea Del Sur",
                    "Slovenia":"Eslovenia",
                    "North Korea":"Corea Del Norte",
                    "Sierra Leone":"Sierra Leona",
                    "Solomon Islands":"Islas Salomón",
                    "Saudi Arabia":"Arabia Saudita",
                    "Sweden":"Suecia",
                    "Sudan":"Sudán",
                    "Dominican Republic":"República Dominicana",
                    "Denmark":"Dinamarca",
                    "Germany":"Alemania",
                    "Algeria":"Argelia",
                    "United States of America":"Estados Unidos de América",
                    "Latvia":"Letonia",
                    "Lebanon":"Líbano",
                    "Taiwan":"Taiwán",
                    "Trinidad and Tobago":"Trinidad y Tobago",
                    "Turkey":"Pavo",
                    "Tunisia":"Túnez",
                    "East Timor":"Timor Oriental",
                    "Turkmenistan":"Turkmenistán",
                    "Tajikistan":"Tayikistán",
                    "Lesotho":"Lesoto",
                    "Thailand":"Tailandia",
                    "French Southern and Antarctic Lands":"Tierras Australes y Antárticas Francesas",
                    "Togo":"Ir",
                    "Libya":"Libia",
                    "United Arab Emirates":"Emiratos Árabes Unidos",
                    "Afghanistan":"Afganistán",
                    "Iraq":"Irak",
                    "Iceland":"Islandia",
                    "Iran":"Irán",
                    "Italy":"Italia",
                    "Azerbaijan":"Azerbaiyán",
                    "Ireland":"Irlanda",
                    "Ukraine":"Ucrania",
                    "Qatar":"Katar"
                }
            },
            "Swedish": {
                "vizMsg":"Klicka på platser för att jämföra",
                "cubeMsg":"Klicka på kartan för att visa",
                "in":"i",
                "data":"källdata",
                "cor":"korrelationskoefficient",
                "rank":"Placering",
                "by":"av",
                "graph":"graf",
                "reset":"återställ",
                "play":"spela",
                "forward":"steg framåt",
                "backward":"steg bakåt",
                "months": ["jan.", "febr.", "mars", "april", "maj", "juni", "juli", "aug.", "sept.", "okt.", "nov.", "dec."],
                geonames: {
                    "Belgium":"Belgien",
                    "Bulgaria":"Bulgarien",
                    "Bosnia and Herzegovina":"Bosnien och Hercegovina",
                    "Brazil":"Brasilien",
                    "The Bahamas":"Bahamas",
                    "Belarus":"Vitryssland",
                    "Russia":"Ryssland",
                    "Republic of Serbia":"Republiken Serbien",
                    "Lithuania":"Litauen",
                    "Luxembourg":"Luxemburg",
                    "Romania":"Rumänien",
                    "Guinea Bissau":"Guinea-Bissau",
                    "Greece":"Grekland",
                    "Equatorial Guinea":"Ekvatorialguinea",
                    "Georgia":"Georgien",
                    "United Kingdom":"Storbritannien",
                    "Greenland":"Grönland",
                    "Somaliland":"Somali",
                    "Western Sahara":"Västsahara",
                    "Northern Cyprus":"Norra Cypern",
                    "Jordan":"Jordanien",
                    "Croatia":"Kroatien",
                    "Hungary":"Ungern",
                    "West Bank":"Västbanken",
                    "Papua New Guinea":"Papua Nya Guinea",
                    "Philippines":"Filippinerna",
                    "Poland":"Polen",
                    "Zambia":"Zambias",
                    "Estonia":"Estland",
                    "Egypt":"Egypten",
                    "South Africa":"Sydafrika",
                    "Albania":"Albanien",
                    "Kazakhstan":"Kazakstan",
                    "Ethiopia":"Etiopien",
                    "Spain":"Spanien",
                    "Moldova":"Moldavien",
                    "Madagascar":"Madagaskar",
                    "Morocco":"Marocko",
                    "Mongolia":"Mongoliet",
                    "Macedonia":"Makedonien",
                    "Mauritania":"Mauretanien",
                    "Mexico":"Mexiko",
                    "France":"Frankrike",
                    "Falkland Islands":"Falklandsöarna",
                    "Netherlands":"Nederländerna",
                    "Norway":"Norge",
                    "New Caledonia":"Nya Kaledonien",
                    "New Zealand":"Nya Zeeland",
                    "Ivory Coast":"Elfenbenskusten",
                    "Switzerland":"Schweiz",
                    "China":"Kina",
                    "Cameroon":"Kamerun",
                    "Canada":"Kanada",
                    "Republic of the Congo":"Republiken Kongo",
                    "Central African Republic":"Centralafrikanska republiken",
                    "Democratic Republic of the Congo":"Demokratiska republiken Kongo",
                    "Czech Republic":"Tjeckien",
                    "Cyprus":"Cypern",
                    "Cuba":"Kuba",
                    "Syria":"Syrien",
                    "South Sudan":"Södra Sudan",
                    "Suriname":"Surinam",
                    "Cambodia":"Kambodja",
                    "Slovakia":"Slovakien",
                    "South Korea":"Sydkorea",
                    "Slovenia":"Slovenien",
                    "North Korea":"Nordkorea",
                    "Solomon Islands":"SALOMONÖARNA",
                    "Saudi Arabia":"Saudiarabien",
                    "Sweden":"Sverige",
                    "Dominican Republic":"Dominikanska Republiken",
                    "Denmark":"Danmark",
                    "Germany":"Tyskland",
                    "Yemen":"Jemen",
                    "Austria":"Österrike",
                    "Algeria":"Algeriet",
                    "United States of America":"USA",
                    "Latvia":"Lett",
                    "Lebanon":"Libanon",
                    "Trinidad and Tobago":"Trinidad och Tobago",
                    "Turkey":"Kalkon",
                    "Tunisia":"Tunisien",
                    "East Timor":"Östtimor",
                    "Tajikistan":"Tadzjikistan",
                    "French Southern and Antarctic Lands":"Franska sydliga och antarktiska Lands",
                    "Chad":"Tchad",
                    "Libya":"Libyen",
                    "United Arab Emirates":"Förenade Arabemiraten",
                    "Iraq":"Irak",
                    "Iceland":"Island",
                    "Armenia":"Armenien",
                    "Italy":"Italien",
                    "Australia":"Australien",
                    "India":"Indien",
                    "Azerbaijan":"Azerbajdzjan",
                    "Ireland":"Irland",
                    "Indonesia":"Indonesien",
                    "Ukraine":"Ukraina",
                    "Mozambique":"Moçambique"
                }
            },
            "Norwegian": {
                "vizMsg":"Klikk steder å sammenligne",
                "cubeMsg":"Klikk på kartet for å vise",
                "in":"i",
                "src":"drevet av MashableData",
                "cor":"korrelasjonskoeffisient",
                "by":"av",
                "graph":"graf",
                "play":"spille",
                "forward":"skritt fremover",
                "backward":"gå bakover",
                "months": ["jan.", "febr.", "mars", "april", "mai", "juni", "juli", "aug.", "sept.", "okt.", "nov.", "des."],
                geonames: {
                    "Belgium":"Belgia",
                    "Bosnia and Herzegovina":"Bosnia-Hercegovina",
                    "Brazil":"Brasil",
                    "The Bahamas":"Bahamas",
                    "Belarus":"Hviterussland",
                    "Russia":"Russland",
                    "Republic of Serbia":"Republikken Serbia",
                    "Lithuania":"Litauen",
                    "Greece":"Hellas",
                    "Equatorial Guinea":"Ekvatorial-Guinea",
                    "United Kingdom":"Storbritannia",
                    "Greenland":"Grønland",
                    "Western Sahara":"Vest-Sahara",
                    "Northern Cyprus":"Nord-Kypros",
                    "Croatia":"Kroatia",
                    "Hungary":"Ungarn",
                    "West Bank":"Vestbredden",
                    "Papua New Guinea":"Papua Ny-Guinea",
                    "Philippines":"Filippinene",
                    "Poland":"Polen",
                    "Estonia":"Estland",
                    "South Africa":"Sør-Afrika",
                    "Kazakhstan":"Kasakhstan",
                    "Ethiopia":"Etiopia",
                    "Spain":"Spania",
                    "Madagascar":"Madagaskar",
                    "Morocco":"Marokko",
                    "Uzbekistan":"Usbekistan",
                    "Macedonia":"Makedonia",
                    "France":"Frankrike",
                    "Falkland Islands":"Falklandsøyene",
                    "Netherlands":"Nederland",
                    "Norway":"Norge",
                    "New Caledonia":"Ny-Caledonia",
                    "Ivory Coast":"Elfenbenskysten",
                    "Switzerland":"Sveits",
                    "China":"Porselen",
                    "Cameroon":"Kamerun",
                    "Republic of the Congo":"Republikken Kongo",
                    "Central African Republic":"Den sentralafrikanske republikk",
                    "Democratic Republic of the Congo":"Den demokratiske republikken Kongo",
                    "Czech Republic":"Tsjekkisk Republikk",
                    "Cyprus":"Kypros",
                    "Kyrgyzstan":"Kirgisistan",
                    "South Sudan":"Sør-Sudan",
                    "Suriname":"Surinam",
                    "Cambodia":"Kambodsja",
                    "South Korea":"Sør-Korea",
                    "North Korea":"Nord-Korea",
                    "Solomon Islands":"Salomonøyene",
                    "Sweden":"Sverige",
                    "Dominican Republic":"Den Dominikanske Republikk",
                    "Denmark":"Danmark",
                    "Germany":"Tyskland",
                    "Yemen":"Jemen",
                    "Austria":"Østerrike",
                    "Algeria":"Algerie",
                    "United States of America":"Amerikas forente stater",
                    "Lebanon":"Libanon",
                    "Trinidad and Tobago":"Trinidad og Tobago",
                    "Turkey":"Kalkun",
                    "East Timor":"Øst-Timor",
                    "Tajikistan":"Tadsjikistan",
                    "French Southern and Antarctic Lands":"Franske sørlige og antarktiske Lands",
                    "Togo":"Å Gå",
                    "Chad":"Tsjad",
                    "United Arab Emirates":"De forente arabiske emirater",
                    "Iraq":"Irak",
                    "Italy":"Italia",
                    "Azerbaijan":"Aserbajdsjan",
                    "Ireland":"Irland",
                    "Ukraine":"Ukraina",
                    "Mozambique":"Mosambik"
                }
            },
            "Danish": {
                "vizMsg":"klik steder at sammenligne",
                "cubeMsg":"klik på kortet for at se",
                "in":"i",
                "src":"drevet af MashableData",
                "data":"kildedata",
                "cor":"korrelationskoefficient",
                "by":"ved",
                "graph":"graf",
                "play":"spille",
                "forward":"skridt fremad",
                "backward":"træde baglæns",
                "months": ["jan.", "febr.", "marts", "april", "maj", "juni", "juli", "aug.", "sept.", "okt.", "nov.", "dec."],
                geonames: {
                    "Belgium":"Belgien",
                    "Bulgaria":"Bulgarien",
                    "Bosnia and Herzegovina":"Bosnien-Hercegovina",
                    "Brazil":"Brasilien",
                    "The Bahamas":"Bahamas",
                    "Belarus":"Hviderusland",
                    "Russia":"Rusland",
                    "Republic of Serbia":"Republikken Serbien",
                    "Lithuania":"Litauen",
                    "Romania":"Rumænien",
                    "Guinea Bissau":"Guinea-Bissau",
                    "Greece":"Grækenland",
                    "Equatorial Guinea":"Ækvatorial Guinea",
                    "Georgia":"Georgien",
                    "United Kingdom":"Storbritannien",
                    "Greenland":"Grønland",
                    "Western Sahara":"Vestsahara",
                    "Northern Cyprus":"Nordcypern",
                    "Croatia":"Kroatien",
                    "Hungary":"Ungarn",
                    "Papua New Guinea":"Papua Ny Guinea",
                    "Philippines":"Filippinerne",
                    "Poland":"Polen",
                    "Estonia":"Estland",
                    "Egypt":"Egypten",
                    "South Africa":"Sydafrika",
                    "Albania":"Albanien",
                    "Kazakhstan":"Kasakhstan",
                    "Ethiopia":"Etiopien",
                    "Spain":"Spanien",
                    "Madagascar":"Madagaskar",
                    "Morocco":"Marokko",
                    "Uzbekistan":"Usbekistan",
                    "Mongolia":"Mongoliet",
                    "Macedonia":"Makedonien",
                    "Mauritania":"Mauretanien",
                    "France":"Frankrig",
                    "Falkland Islands":"Falklandsøerne",
                    "Netherlands":"Holland",
                    "Norway":"Norge",
                    "New Caledonia":"Ny Kaledonien",
                    "Ivory Coast":"Elfenbenskysten",
                    "Switzerland":"Schweiz",
                    "China":"Porcelæn",
                    "Republic of the Congo":"Republikken Congo",
                    "Central African Republic":"Centralafrikanske Republik",
                    "Democratic Republic of the Congo":"Den Demokratiske Republik Congo",
                    "Czech Republic":"Tjekkiet",
                    "Cyprus":"Cypern",
                    "Syria":"Syrien",
                    "Kyrgyzstan":"Kirgisistan",
                    "South Sudan":"Sydsudan",
                    "Suriname":"Surinam",
                    "Cambodia":"Cambodja",
                    "Slovakia":"Slovakiet",
                    "South Korea":"Sydkorea",
                    "Slovenia":"Slovenien",
                    "North Korea":"Nordkorea",
                    "Solomon Islands":"Salomonøerne",
                    "Saudi Arabia":"Saudi-Arabien",
                    "Sweden":"Sverige",
                    "Dominican Republic":"Den Dominikanske Republik",
                    "Denmark":"Danmark",
                    "Germany":"Tyskland",
                    "Austria":"Østrig",
                    "Algeria":"Algeriet",
                    "United States of America":"USA",
                    "Latvia":"Letland",
                    "Lebanon":"Libanon",
                    "Trinidad and Tobago":"Trinidad og Tobago",
                    "Turkey":"Kalkun",
                    "Tunisia":"Tunesien",
                    "East Timor":"Østtimor",
                    "Tajikistan":"Tadsjikistan",
                    "French Southern and Antarctic Lands":"Franske sydlige og antarktiske Lands",
                    "Libya":"Libyen",
                    "United Arab Emirates":"De Forenede Arabiske Emirater",
                    "Iraq":"Irak",
                    "Iceland":"Island",
                    "Armenia":"Armenien",
                    "Italy":"Italien",
                    "Australia":"Australien",
                    "India":"Indien",
                    "Azerbaijan":"Aserbajdsjan",
                    "Ireland":"Irland",
                    "Indonesia":"Indonesien"
                }
            },
            "Dutch": {
                "vizMsg":"Klik locaties om te vergelijken",
                "cubeMsg":"Klik op de kaart om te bekijken",
                "src":"aangedreven door MashableData",
                "data":"brongegevens",
                "cor":"correlatiecoëfficiënt",
                "rank":"Rang",
                "by":"door",
                "graph":"diagram",
                "play":"spelen",
                "forward":"stap voorwaarts",
                "backward":"stap achteruit",
                "months": ["jan.", "feb.", "maart", "apr.", "mei", "juni", "juli", "aug.", "sept.", "okt.", "nov.", "dec."],
                geonames: {
                    "Belgium":"België",
                    "Bulgaria":"Bulgarije",
                    "Bosnia and Herzegovina":"Bosnië-Herzegovina",
                    "Burundi":"Boeroendi",
                    "Brazil":"Brazilië",
                    "The Bahamas":"De Bahama's",
                    "Belarus":"Wit-Rusland",
                    "Russia":"Rusland",
                    "Republic of Serbia":"Republiek Servië",
                    "Lithuania":"Litouwen",
                    "Luxembourg":"Luxemburg",
                    "Romania":"Roemenië",
                    "Guinea Bissau":"Guinee-Bissau",
                    "Greece":"Griekenland",
                    "Equatorial Guinea":"Equatoriaal-Guinea",
                    "United Kingdom":"Verenigd Koninkrijk",
                    "Greenland":"Groenland",
                    "Kuwait":"Koeweit",
                    "Western Sahara":"Westelijke Sahara",
                    "Northern Cyprus":"Noord-Cyprus",
                    "Jordan":"Jordanië",
                    "Croatia":"Kroatië",
                    "Haiti":"Haïti",
                    "Hungary":"Hongarije",
                    "West Bank":"Westelijke Jordaanoever",
                    "Papua New Guinea":"Papoea-Nieuw-Guinea",
                    "Philippines":"Filippijnen",
                    "Poland":"Polen",
                    "Estonia":"Estland",
                    "Egypt":"Egypte",
                    "South Africa":"Zuid-Afrika",
                    "Albania":"Albanië",
                    "Ethiopia":"Ethiopië",
                    "Spain":"Spanje",
                    "Moldova":"Moldavië",
                    "Morocco":"Marokko",
                    "Uzbekistan":"Oezbekistan",
                    "Mongolia":"Mongolië",
                    "Macedonia":"Macedonië",
                    "Mauritania":"Mauritanië",
                    "Uganda":"Oeganda",
                    "Malaysia":"Maleisië",
                    "France":"Frankrijk",
                    "Falkland Islands":"Falkland Eilanden",
                    "Netherlands":"Nederland",
                    "Norway":"Noorwegen",
                    "Namibia":"Namibië",
                    "New Caledonia":"Nieuw-Caledonië",
                    "New Zealand":"Nieuw Zeeland",
                    "Ivory Coast":"Ivoorkust",
                    "Switzerland":"Zwitserland",
                    "Cameroon":"Kameroen",
                    "Chile":"Chili",
                    "Republic of the Congo":"Republiek Congo",
                    "Central African Republic":"Centraal-Afrikaanse Republiek",
                    "Democratic Republic of the Congo":"Democratische Republiek Congo",
                    "Czech Republic":"Tsjechische Republiek",
                    "Syria":"Syrië",
                    "Kyrgyzstan":"Kirgizië",
                    "Kenya":"Kenia",
                    "South Sudan":"Zuid-Soedan",
                    "Cambodia":"Cambodja",
                    "Slovakia":"Slowakije",
                    "South Korea":"Zuid-Korea",
                    "Slovenia":"Slovenië",
                    "North Korea":"Noord Korea",
                    "Somalia":"Somalië",
                    "Saudi Arabia":"Saoedi-Arabië",
                    "Sweden":"Zweden",
                    "Sudan":"Soedan",
                    "Dominican Republic":"Dominicaanse Republiek",
                    "Denmark":"Denemarken",
                    "Germany":"Duitsland",
                    "Yemen":"Jemen",
                    "Austria":"Oostenrijk",
                    "Algeria":"Algerije",
                    "United States of America":"Verenigde Staten van Amerika",
                    "Latvia":"Letland",
                    "Lebanon":"Libanon",
                    "Trinidad and Tobago":"Trinidad en Tobago",
                    "Turkey":"Turkije",
                    "Tunisia":"Tunesië",
                    "East Timor":"Oost-Timor",
                    "Tajikistan":"Tadzjikistan",
                    "French Southern and Antarctic Lands":"Franse Zuidelijke en Antarctische gebieden",
                    "Togo":"Gaan",
                    "Chad":"Tsjaad",
                    "Libya":"Libië",
                    "United Arab Emirates":"Verenigde Arabische Emiraten",
                    "Iraq":"Irak",
                    "Iceland":"IJsland",
                    "Armenia":"Armenië",
                    "Italy":"Italië",
                    "Argentina":"Argentinië",
                    "Australia":"Australië",
                    "Israel":"Israël",
                    "India":"Indië",
                    "Azerbaijan":"Azerbeidzjan",
                    "Ireland":"Ierland",
                    "Indonesia":"Indonesië",
                    "Ukraine":"Oekraïne",
                    "Qatar":"Katar"
                }
            },
            "Italian": {
                "vizMsg":"clicca posizioni per confrontare",
                "cubeMsg":"clicca sulla mappa per visualizzare",
                "data":"dati di origine",
                "cor":"coefficiente di correlazione",
                "rank":"Rango",
                "by":"da",
                "graph":"grafico",
                "play":"giocare",
                "forward":"passo avanti",
                "backward":"passo indietro",
                "months": ["genn.", "febbr.", "mar.", "apr.", "magg.", "giugno", "luglio", "ag.", "sett.", "ott.", "nov.", "dic."],
                geonames: {
                    "Belgium":"Belgio",
                    "Bosnia and Herzegovina":"Bosnia Erzegovina",
                    "Japan":"Giappone",
                    "Jamaica":"Giamaica",
                    "Brazil":"Brasile",
                    "The Bahamas":"Bahamas",
                    "Belarus":"Bielorussia",
                    "Rwanda":"Ruanda",
                    "Republic of Serbia":"Repubblica di Serbia",
                    "Lithuania":"Lituania",
                    "Luxembourg":"Lussemburgo",
                    "Guinea Bissau":"Guinea-Bissau",
                    "Greece":"Grecia",
                    "Equatorial Guinea":"Guinea Equatoriale",
                    "United Kingdom":"Regno Unito",
                    "Greenland":"Groenlandia",
                    "Western Sahara":"Sahara Occidentale",
                    "Northern Cyprus":"Cipro del Nord",
                    "Jordan":"Giordania",
                    "Croatia":"Croazia",
                    "Hungary":"Ungheria",
                    "West Bank":"Cisgiordania",
                    "Portugal":"Portogallo",
                    "Papua New Guinea":"Papua Nuova Guinea",
                    "Peru":"Perù",
                    "Philippines":"Filippine",
                    "Poland":"Polonia",
                    "Egypt":"Egitto",
                    "South Africa":"Sud Africa",
                    "Kazakhstan":"Kazakistan",
                    "Ethiopia":"Etiopia",
                    "Spain":"Spagna",
                    "Morocco":"Marocco",
                    "Mexico":"Messico",
                    "France":"Francia",
                    "Finland":"Finlandia",
                    "Falkland Islands":"Isole Falkland",
                    "Netherlands":"Paesi Bassi",
                    "Norway":"Norvegia",
                    "New Caledonia":"Nuova Caledonia",
                    "New Zealand":"Nuova Zelanda",
                    "Ivory Coast":"Costa D'Avorio",
                    "Switzerland":"Svizzera",
                    "China":"Porcellana",
                    "Cameroon":"Camerun",
                    "Republic of the Congo":"Repubblica del Congo",
                    "Central African Republic":"Repubblica Centrafricana",
                    "Democratic Republic of the Congo":"Repubblica Democratica del Congo",
                    "Czech Republic":"Repubblica Ceca",
                    "Cyprus":"Cipro",
                    "Syria":"Siria",
                    "Kenya":"Kenia",
                    "South Sudan":"Sud Sudan",
                    "Cambodia":"Cambogia",
                    "Slovakia":"Slovacchia",
                    "South Korea":"Corea Del Sud",
                    "North Korea":"Nord Corea",
                    "Solomon Islands":"Isole Salomone",
                    "Saudi Arabia":"Arabia Saudita",
                    "Sweden":"Svezia",
                    "Dominican Republic":"Repubblica Dominicana",
                    "Denmark":"Danimarca",
                    "Germany":"Germania",
                    "United States of America":"Stati Uniti d'America",
                    "Latvia":"Lettonia",
                    "Lebanon":"Libano",
                    "Trinidad and Tobago":"Trinidad e Tobago",
                    "Turkey":"Tacchino",
                    "East Timor":"Timor Est",
                    "Lesotho":"Lesoto",
                    "Thailand":"Thailandia",
                    "French Southern and Antarctic Lands":"Terre australi e antartiche francesi",
                    "Togo":"Andare",
                    "Libya":"Libia",
                    "United Arab Emirates":"Emirati Arabi Uniti",
                    "Iceland":"Islanda",
                    "Iran":"Ho Corso",
                    "Italy":"Italia",
                    "Israel":"Israele",
                    "Ireland":"Irlanda",
                    "Ukraine":"Ucraina",
                    "Mozambique":"Mozambico"
                }
            }
        }
    }
};
if(typeof console == 'undefined') console = {info: function(m){}, log: function(m){}};  //allow console.log call without triggering errors in IE or FireFox w/o Firebug
